### ISSUE TITLE
Problem with type when trying to use plugin

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor-plugin#2]
Hello, when I try to use the docx plugin the following error appears regarding the type of the docxPlugin function:

instance.use(docxPlugin) show:
```
Argument of type '(editor: Editor) => void' is not assignable to parameter of type 'PluginFunction<unknown>'.
  Types of parameters 'editor' and 'editor' are incompatible.
    Type 'import("e:/Downloads/projects/canvas-editor-versions/compile-to-polisoftware/canvas-editor/src/editor/index").default' is not assignable to type 'import("e:/Downloads/projects/canvas-editor-versions/compile-to-polisoftware/canvas-editor/node_modules/@hufe921/canvas-editor/dist/src/editor/index").default'.
      Types of property 'eventBus' are incompatible.
        Type 'import("e:/Downloads/projects/canvas-editor-versions/compile-to-polisoftware/canvas-editor/src/editor/core/event/eventbus/EventBus").EventBus<import("e:/Downloads/projects/canvas-editor-versions/compile-to-polisoftware/canvas-editor/src/editor/interface/EventBus").EventBusMap>' is not assignable to type 'import("e:/Downloads/projects/canvas-editor-versions/compile-to-polisoftware/canvas-editor/node_modules/@hufe921/canvas-editor/dist/src/editor/core/event/eventbus/EventBus").EventBus<import("e:/Downloads/projects/canvas-editor-versions/compile-to-polisoftware/canvas-editor/node_modules/@hufe921/canvas-editor/dist/sr...'.
          Types have separate declarations of a private property 'eventHub'.ts(2345)
```

And <CommandWithDocx>instance.command show:
```
Conversion of type 'Command' to type 'CommandWithDocx' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'executeExportDocx' is missing in type 'Command' but required in type '{ executeExportDocx(options: IExportDocxOption): void; }'.ts(2352)
```

Excuse my ignorance, but I'm new to typescript, so I was confused on how to proceed, isn't the PluginFunction type the same as the imported function docxPlugin ? How do I adjust this? Thanks in advance.

**Comment by douglasmatheus** [comment]
I managed to solve it by placing the plugin sources within the project instead of importing and it worked like this.

**Comment by Hufe921** [comment]
```typescript
import docxPlugin, { CommandWithDocx } from "@hufe921/canvas-editor-plugin-docx"
editor.use(docxPlugin)
const command = editor.command as CommandWithDocx
command.executeExportDocx()
```

**Comment by douglasmatheus** [comment]
I tried this way, but the error persisted, I think it's because I made general changes to the editor's core. Well, I started a new project and the import worked. However, the build did not run and asked to configure the option:
```
rollupOptions: {
       external: ['@hufe921/canvas-editor']
}
```

Finally I chose to place the puglin scripts directly in the project that I changed and it worked.

By the way, I made improvements in the export of table styles, all width, alignment, background, in lists, adjusted the type of list that was generating only the numbered type, page break and document margins. Would you like a PR to be sent for analysis?

**Comment by Hufe921** [comment]
upgrade:  "@hufe921/canvas-editor-plugin-docx": "0.0.4"

**Comment by Hufe921** [comment]
> I tried this way, but the error persisted, I think it's because I made general changes to the editor's core. Well, I started a new project and the import worked. However, the build did not run and asked to configure the option:
> 
> ```
> rollupOptions: {
>        external: ['@hufe921/canvas-editor']
> }
> ```
> 
> Finally I chose to place the puglin scripts directly in the project that I changed and it worked.
> 
> By the way, I made improvements in the export of table styles, all width, alignment, background, in lists, adjusted the type of list that was generating only the numbered type, page break and document margins. Would you like a PR to be sent for analysis?

Welcome to submit PR

**Comment by lizhongyue248** [comment]
0.0.5 版本貌似没有 CommandWithDocx？TS 里面找不到 executeImportDocx

![image](https://github.com/user-attachments/assets/e3bfb1c4-2bb8-4a19-9155-89172596e98e)
