### ISSUE TITLE
canvas-editor-plugin-docx 报错，求指点

### ISSUE THREAD

**Issue by 15136610015** [Hufe921/canvas-editor-plugin#7]
@hufe921/canvas-editor-plugin-docx
是不是vue不能用呀，按照引用报错index.vue:37 Uncaught (in promise) TypeError: editorInstance.executeExportDocx is not a function
求大佬指点。

**Comment by Hufe921** [comment]
确认是否安装插件，并正确使用，如果还不行给出复现demo

**Comment by 15136610015** [comment]
谢谢。已经找到问题，是我菜了

**Comment by 54546586** [comment]
你好 怎么解决的呢
